service: nasa-launch-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  handleNasaLaunch:
    handler: src/server.handleNasaLaunch
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true