name: Nasa Launch CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js Version 20
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: npm install
            - run: cd ./server && npm install
            - run: cd ./client && npm install
            - run: npm run build --prefix client
